const OFFICIAL_KEYS_2025 = {136:"C",137:"E",138:"C",139:"C",140:"A",141:"D",142:"D",143:"B",144:"E",145:"B",146:"C",147:"A",148:"C",149:"E",150:"C",151:"B",152:"D",153:"D",154:"D",155:"B",156:"A",157:"D",158:"E",159:"E",160:"A",161:"B",162:"B",163:"E",164:"C",165:"C",166:"D",167:"A",168:"B",169:"E",170:"A",171:"D",172:"D",173:"E",174:"B",175:"E",176:"A",177:"A",178:null,179:"C",180:"C"};
const KNOWN_OFFICIAL_PAGE_HINTS={"2025-144":18};
function isExtractionArtifact(value){const t=String(value??"").trim();if(!t)return false;return(/^\*?\d{6,}[A-Z]{1,5}\d*\*?$/i.test(t)||/^\*?0?20\d{2}\d*[A-Z0-9]+\*?$/i.test(t)||/^ENEM20\d{2}(?:ENEM20\d{2})+/i.test(t)||/MATEM[ÁA]TICA E SUAS TECNOLOGIAS\s*\|\s*2[ºO]\s*DIA/i.test(t)||/CADERNO\s*5\s*\|\s*AMARELO/i.test(t));}
function cleanAlternativeRaw(value){const raw=String(value??"").replace(/\r/g,"");const lines=raw.split(/\n+/).map(x=>x.trim()).filter(x=>x&&!isExtractionArtifact(x)&&!/^ENEM20\d{2}/i.test(x));return lines.join("\n").trim();}
function alternativeMathTex(raw){const clean=cleanAlternativeRaw(raw);if(!clean)return null;const lines=clean.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(lines.length===2&&lines.every(x=>/^[−-]?\d+(?:[.,]\d+)?$/.test(x))){const[n,d]=lines;return `\\(\\dfrac{${n.replace(",",".")}}{${d.replace(",",".")}}\\)`;}if(clean.length<=70&&/^[A-Za-zÀ-ÿ0-9π√∆Δ()+\-−=<>≤≥²³^/*·×÷.,:%\s]+$/.test(clean)&&/[=<>≤≥²³^/*·×÷√π∆Δ]/.test(clean)){let tex=clean.replace(/−/g,"-").replace(/×/g,"\\times ").replace(/·/g,"\\cdot ").replace(/÷/g,"\\div ").replace(/π/g,"\\pi ").replace(/²/g,"^2").replace(/³/g,"^3");return `\\(${tex}\\)`;}return null;}
function auditAlternatives(q){const alts=q.alternatives||[],usable=alts.filter(a=>(a.text&&a.text.trim())||a.file).length,blank=alts.filter(a=>!(a.text&&a.text.trim())&&!a.file).length,visualCue=/figura|proje[cç][aã]o|proje[cç][oõ]es|gr[aá]fico|diagrama|imagem|desenho|planifica[cç][aã]o/i.test(`${q.context||""} ${q.alternativesIntroduction||""}`),visualOnly=alts.length===5&&blank>=3&&visualCue,incomplete=alts.length!==5||usable<5;return{usable,blank,visualCue,visualOnly,incomplete};}
function alternativeDisplayHtml(a,visualOnly=false){const letter=escapeHtml(a.letter);if(a.file)return `<span class="answer-text"><span class="alt-letter">${letter})</span>${a.text?inlineQuestionText(a.text):""}</span><img class="alternative-image" loading="lazy" src="${escapeHtml(a.file)}" alt="Figura da alternativa ${letter}">`;if(a.mathTex)return `<span class="answer-text"><span class="alt-letter">${letter})</span><span class="alt-math">${a.mathTex}</span></span>`;if(a.text)return `<span class="answer-text"><span class="alt-letter">${letter})</span>${inlineQuestionText(a.text)}</span>`;return `<span class="answer-text missing-alt"><span class="alt-letter">${letter})</span><span>${visualOnly?"alternativa em figura — veja a página original abaixo":"conteúdo não preservado na extração"}</span></span>`;}
function officialPreviewUrl(q){if(Number(q.year)===2025)return "https://riep.inep.gov.br/bitstreams/d43be9d0-2316-42bf-9ea7-dc4475645c52/download";return q.officialPdf;}
let pdfJsPromise=null;
function ensurePdfJs(){if(window.pdfjsLib)return Promise.resolve(window.pdfjsLib);if(pdfJsPromise)return pdfJsPromise;pdfJsPromise=new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js";s.onload=()=>{if(!window.pdfjsLib)return reject(new Error("PDF.js não carregou."));window.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";resolve(window.pdfjsLib);};s.onerror=()=>reject(new Error("Não foi possível carregar o visualizador de PDF."));document.head.appendChild(s);});return pdfJsPromise;}
function normalizeSearchText(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g,"").replace(/[^a-z0-9]/g,"");}
async function findQuestionPage(pdf,q){const cacheKey=`${q.year}-${q.index}`;if(state.pdfPageCache?.has(cacheKey))return state.pdfPageCache.get(cacheKey);const hinted=KNOWN_OFFICIAL_PAGE_HINTS[cacheKey];if(hinted){state.pdfPageCache.set(cacheKey,hinted);return hinted;}const needleContext=normalizeSearchText((q.context||"").slice(0,90)),needleNumber=`questao${q.index}`,first=Math.max(1,Math.floor(pdf.numPages*.38));for(let n=first;n<=pdf.numPages;n++){const page=await pdf.getPage(n),tc=await page.getTextContent(),pageText=normalizeSearchText(tc.items.map(i=>i.str).join(" "));if(pageText.includes(needleNumber)||(needleContext.length>20&&pageText.includes(needleContext.slice(0,50)))){state.pdfPageCache.set(cacheKey,n);return n;}}return null;}
