const CLASS_RULES = {
  geometria: [[/\b(geometr|triang|retang|quadrad|losang|trap[eé]z|pol[ií]gon|circunfer|c[ií]rcul|raio|di[aâ]metro|per[ií]metro|[aá]rea|volume|prisma|pir[aâ]mid|cilindr|cone|esfera|cubo|paralelep[ií]ped|poliedr|v[eé]rtice|aresta|face|semelhan|pit[aá]gor|[aâ]ngulo|planifica|coordenad|plano cartesiano|proje[cç][aã]o ortogonal|proje[cç][oõ]es ortogonais|plano xy|plano xz|plano yz|eixos coordenados)\w*/g,3],[/\b(planta|maquete|mapa|escala)\w*/g,1.5]],
  graficos: [[/\b(gr[aá]fic|tabela|quadro|histograma|infogr[aá]fic|diagrama|eixo|coluna|barra|setor)\w*/g,3],[/\b(representa[cç][aã]o|curva|linha do gr[aá]fico)\w*/g,1]],
  proporcao: [[/\b(porcent|percent|propor[cç]|raz[aã]o|regra de tr[eê]s|taxa|escala|diretamente proporcional|inversamente proporcional)\w*/g,3],[/\b(desconto|acr[eé]scimo|rendimento|consumo|a cada|receita|pre[cç]o|custo)\w*/g,1.2]],
  unidades: [[/\b(convers[aã]o|unidade de medida|medida em|quil[oô]metr|cent[ií]metr|mil[ií]metr|metro c[uú]bico|metro quadrado|litro|mililitro|quilograma|grama|tonelada|hectare)\w*/g,2.5],[/\b(km|cm|mm|m²|m2|m³|m3|ml|kg|g\/cm|km\/h|m\/s)\b/g,1.6]],
  estatistica: [[/\b(estat[ií]st|m[eé]dia|mediana|moda|desvio|vari[aâ]ncia|amostra|frequ[eê]ncia|quartil|distribui[cç][aã]o|histograma)\w*/g,3],[/\b(dados|levantamento|pesquisa)\w*/g,.8]],
  funcoes: [[/\b(fun[cç][aã]o|f\(x\)|g\(x\)|h\(x\)|equa[cç][aã]o|inequa[cç][aã]o|express[aã]o alg[eé]brica|coeficiente|raiz da fun[cç][aã]o|dom[ií]nio|imagem da fun[cç][aã]o)\w*/g,3],[/\b(logarit|exponencial|progress[aã]o|sequ[eê]ncia|termo geral|juros|capital|montante)\w*/g,2.3],[/\b(sistema de equa[cç][oõ]es|matriz|polin[oô]mio)\w*/g,2.5]],
  probabilidade: [[/\b(probabil|combinat|permuta|arranjo|combina[cç][aã]o|princ[ií]pio multiplicativo|espa[cç]o amostral)\w*/g,3],[/\b(sorteio|sortead|ao acaso|aleatori|chance|possibilidades|senha|c[oó]digo|dado|moeda|urna)\w*/g,1.6]]
};
function stripAccents(s){return (s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"");}
function questionTextForClassification(q){return [q.context||"",q.alternativesIntroduction||"",...(q.alternatives||[]).map(a=>a.text||"")].join(" ").toLowerCase();}
function classifyQuestion(q){
  const raw=questionTextForClassification(q),text=stripAccents(raw),scores={};
  for(const [family,rules] of Object.entries(CLASS_RULES)){let score=0;for(const [regex,weight] of rules){regex.lastIndex=0;const m=text.match(regex);if(m)score+=Math.min(m.length,4)*weight;}scores[family]=score;}
  if(/grafico|tabela|histograma/.test(text))scores.graficos+=2.5;if(/media|mediana|moda|desvio/.test(text))scores.estatistica+=3;if(/probabilidade|sorteio|ao acaso|aleatori/.test(text))scores.probabilidade+=3;if(/area|volume|perimetro|triangulo|circulo|cilindro|cone|prisma|piramide|esfera/.test(text))scores.geometria+=2;if(/porcent|proporcional|razao|escala/.test(text))scores.proporcao+=2;if(/funcao|f\(x\)|equacao|logarit|exponencial|progressao/.test(text))scores.funcoes+=2;if(/km|cm|mm|litro|ml|quilograma|kg|hectare|m²|m³/.test(raw))scores.unidades+=1.5;
  if(/cubo|paralelepiped|projecao ortogonal|projecoes ortogonais|plano xy|plano xz|plano yz|eixos coordenados/.test(text)){scores.geometria+=12;scores.graficos=Math.max(0,scores.graficos-4);}if(/grafico|tabela|histograma|infografico|grafico de barras|grafico de linhas|grafico de setores/.test(text))scores.graficos+=4;
  let ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);if(ranked[0][1]===0){if(/preco|custo|dinheiro|reais|r\$|consumo|rendimento/.test(text))scores.proporcao=1;else scores.funcoes=.5;ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);}
  const max=ranked[0][1],primary=ranked[0][0],families=ranked.filter(([_,s],i)=>i===0||(s>=2.5&&s>=max*.42)).map(([f])=>f).slice(0,4),confidence=max>=7?"alta":max>=3.5?"média":"baixa",sub=detectSubtopics(q,primary);return {primary,families,scores,confidence,primarySubtopic:sub.primary,subtopics:sub.list};
}
function officialPdfUrl(year){if(year<=2013)return `https://download.inep.gov.br/educacao_basica/enem/provas/${year}/dia2_caderno5_amarelo.pdf`;if(year<=2017)return `https://download.inep.gov.br/educacao_basica/enem/provas/${year}/${year}_PV_impresso_D2_CD5.pdf`;if(year===2018)return "https://download.inep.gov.br/educacao_basica/enem/provas/2018/2DIA_05_AMARELO_BAIXA.pdf";if(year===2019)return "https://download.inep.gov.br/educacao_basica/enem/provas/2019/2019_PV_impresso_D2_CD5.pdf";if(year===2025)return "https://riep.inep.gov.br/bitstreams/d43be9d0-2316-42bf-9ea7-dc4475645c52/download";return `https://download.inep.gov.br/enem/provas_e_gabaritos/${year}_PV_impresso_D2_CD5.pdf`;}
