async function fetchSelectedYears(value){if(value!=="all")return fetchYear(Number(value));const all=[],status=document.getElementById("bankStatus");for(let i=0;i<YEARS.length;i++){const year=YEARS[i];if(status)status.innerHTML=`<strong>Carregando corpus completo…</strong><span>${i+1}/${YEARS.length} · ENEM ${year}</span>`;try{all.push(...await fetchYear(year));}catch(e){console.warn("Falha ao carregar",year,e);}}return all.sort((a,b)=>b.year-a.year||a.index-b.index);}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));}
function normalizeExtractedText(value){let s=String(value??"").replace(/\r/g,"");const imgs=[];s=s.replace(/!\[([^\]]*)\]\((https?:\/\/[^)]+)\)/g,(_,alt,url)=>{const token=`@@IMG${imgs.length}@@`;imgs.push({alt,url});return `\n${token}\n`;});s=s.replace(/\b(km|hm|dam|m|dm|cm|mm)\s*\n\s*2\b/gi,"$1²");s=s.replace(/\b(km|hm|dam|m|dm|cm|mm)\s*\n\s*3\b/gi,"$1³");s=s.replace(/\b(km|hm|dam|m|dm|cm|mm)\s*([23])\b/gi,(m,u,p)=>u+(p==="2"?"²":"³"));s=s.replace(/10\s*\n\s*([−-]?\d+)/g,"10^$1");s=s.replace(/([A-Za-z])\s*\n\s*([23])(?=\s*[+\-×·=,.;)])/g,(m,v,p)=>v+(p==="2"?"²":"³"));s=s.replace(/\n{2,}/g,"@@PAR@@");s=s.replace(/\n/g," ");s=s.replace(/[ \t]+/g," ").trim();s=s.replace(/@@PAR@@/g,"\n\n");imgs.forEach((im,i)=>{s=s.replace(`@@IMG${i}@@`,`![${im.alt}](${im.url})`)});return s;}
function formatMathHtml(escaped){let s=escaped;s=s.replace(/\b(km|hm|dam|m|dm|cm|mm)(²|³)\b/g,(_,u,p)=>`<span class="math-unit">${u}<sup>${p==="²"?"2":"3"}</sup></span>`);s=s.replace(/\b(L|mL|kg|mg|g)\b/g,'<span class="math-unit">$1</span>');s=s.replace(/10\^([−-]?\d+)/g,'<span class="math-inline">10<sup>$1</sup></span>');s=s.replace(/([A-Za-z])²/g,'<span class="math-inline">$1<sup>2</sup></span>');s=s.replace(/([A-Za-z])³/g,'<span class="math-inline">$1<sup>3</sup></span>');s=s.replace(/(\d+(?:[.,]\d+)?)\s*%/g,'<span class="math-inline">$1%</span>');return s;}
function renderTextParagraphs(text){const normalized=normalizeExtractedText(text);if(!normalized)return"";return normalized.split(/\n{2,}/).filter(Boolean).map(p=>`<p>${formatMathHtml(escapeHtml(p))}</p>`).join("");}
function richQuestionText(text){const normalized=normalizeExtractedText(text);if(!normalized)return"";const re=/!\[([^\]]*)\]\((https?:\/\/[^)]+)\)/g;let out="",last=0,m;while((m=re.exec(normalized))){const chunk=normalized.slice(last,m.index);out+=chunk.split(/\n{2,}/).filter(x=>x.trim()).map(p=>`<p>${formatMathHtml(escapeHtml(p.trim()))}</p>`).join("");out+=`<figure class="figure-wrap"><img class="question-image" loading="lazy" src="${escapeHtml(m[2])}" alt="${escapeHtml(m[1]||"Figura original da questão")}"><figcaption class="figure-caption">Figura original associada à questão</figcaption></figure>`;last=re.lastIndex;}const tail=normalized.slice(last);out+=tail.split(/\n{2,}/).filter(x=>x.trim()).map(p=>`<p>${formatMathHtml(escapeHtml(p.trim()))}</p>`).join("");return out;}
function inlineQuestionText(text){const normalized=normalizeExtractedText(text);if(!normalized)return"";return formatMathHtml(escapeHtml(normalized).replace(/!\[[^\]]*\]\((https?:\/\/[^)]+)\)/g,"")).replace(/\n{2,}/g," ");}
function subtopicLabel(id){for(const list of Object.values(SUBTOPICS)){const found=list.find(x=>x[0]===id);if(found)return found[1];}return id||"Conteúdo geral";}
function subtopicTagsHtml(q){return(q.subtopics||[]).map(s=>`<span class="subtopic-chip">${escapeHtml(subtopicLabel(s))}</span>`).join("");}
function extractKeyData(q){const s=normalizeExtractedText([q.context,q.alternativesIntroduction].filter(Boolean).join(" ")),re=/(?:R\$\s*)?\d+(?:[.,]\d+)*(?:\s*(?:%|km\/h|m\/s|km|cm|mm|m²|cm²|km²|m³|cm³|L|mL|kg|g|h|min|s|°C|°))?/g,found=s.match(re)||[],uniq=[];for(const x of found){const v=x.trim();if(v&&!uniq.includes(v))uniq.push(v);if(uniq.length>=12)break;}return uniq;}
function buildGuidedSolution(q){const key=q.primarySubtopic||q.subtopics?.[0],method=SOLUTION_METHODS[key]||SOLUTION_METHODS.modelagem_algebrica,caseInfo=detectQuestionCase(q),data=extractKeyData(q),correct=q.alternatives.find(a=>a.letter===q.correctAlternative),correctDisplay=correct?.mathTex||(correct?.text?inlineQuestionText(correct.text):null),target=normalizeExtractedText(q.alternativesIntroduction||"Determine a alternativa que satisfaz as condições do problema.");return `<div class="solution-grid">${caseInfo?`<div class="solution-step case-solution-step"><small>Padrão reconhecido</small><p><strong>${escapeHtml(caseInfo.id)} · ${escapeHtml(caseInfo.title)}</strong></p><p>${escapeHtml(caseInfo.interpret)}</p></div>`:""}<div class="solution-step"><small>1 · O que a questão pede</small><p>${formatMathHtml(escapeHtml(target))}</p></div><div class="solution-step"><small>2 · Método principal · ${escapeHtml(subtopicLabel(key))}</small><p>${method.formula}</p></div>${data.length?`<div class="solution-step"><small>3 · Dados relevantes identificados</small><div class="solution-data">${data.map(x=>`<span class="data-chip">${formatMathHtml(escapeHtml(x))}</span>`).join("")}</div></div>`:""}<div class="solution-step"><small>${data.length?4:3} · Roteiro de resolução</small>${method.steps.map((s,i)=>`<p><strong>${i+1}.</strong> ${escapeHtml(s)}</p>`).join("")}</div><div class="solution-step"><small>Resultado conferido pelo gabarito</small><p><strong>${escapeHtml(q.correctAlternative||"—")}</strong>${correctDisplay?` — ${correctDisplay}`:(q.correctAlternative?` — alternativa ${escapeHtml(q.correctAlternative)} (conteúdo visual na prova original)`:"")}</p></div></div><div class="audit-note">Resolução guiada automática v2: o método e os dados são gerados a partir do conteúdo e do gabarito do item. Itens de baixa confiança devem ser auditados antes de uso como solucionário editorial definitivo.</div>`;}
function triggerMathJax(root=document){if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([root]).catch(()=>{});}
function familyTagsHtml(q){return q.families.map((f,i)=>`<span class="family-chip ${i===0?"primary":""}">${escapeHtml(FAMILY_LABELS[f])}</span>`).join("");}
let extractor2024Promise=null;
async function getExtractor2024(){if(extractor2024Promise)return extractor2024Promise;extractor2024Promise=fetch("https://raw.githubusercontent.com/diaslui/enem-extractor/refs/heads/master/provas/2024/1/output.json",{cache:"force-cache"}).then(r=>{if(!r.ok)throw new Error("Falha no fallback visual 2024");return r.json()}).catch(()=>null);return extractor2024Promise;}
async function enhanceQuestionMedia(q){if(q.year!==2024)return q;const extra=await getExtractor2024(),item=extra?.data?.find(x=>Number(x.number)===Number(q.index));if(!item)return q;const files=(item.content||[]).filter(x=>x.type==="image"&&x.content).map(x=>x.content);if(files.length)q.files=[...new Set([...(q.files||[]),...files])];const altSource=Array.isArray(item.alternatives)?item.alternatives:Object.values(item.alternatives||{});for(const src of altSource){const letter=String(src.alternative||src.letter||"").toUpperCase(),target=q.alternatives.find(a=>a.letter===letter);if(!target)continue;const parts=Array.isArray(src.content)?src.content:[],text=parts.filter(x=>x.type==="text"&&x.content).map(x=>x.content).join(" ").trim(),img=parts.find(x=>x.type==="image"&&x.content)?.content||null;if((!target.text||target.extractionArtifact)&&text){target.rawText=text;target.text=cleanAlternativeRaw(text);target.mathTex=alternativeMathTex(text);target.extractionArtifact=false;}if(!target.file&&img)target.file=img;if(src.correct===true){q.correctAlternative=letter;q.alternatives.forEach(a=>a.isCorrect=a.letter===letter);}}q.alternativeAudit=auditAlternatives(q);return q;}
